apiVersion: v1
kind: Service
metadata:
  name: meadstats-staging
spec:
  selector:
    app: meadstats-staging
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: meadstats-staging-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - staging.meadstats.com
    secretName: meadstats-staging-cert
  rules:
    - host: staging.meadstats.com
      http:
        paths:
        - backend:
            serviceName: meadstats-staging
            servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meadstats-staging-deployment
  labels:
    app: meadstats-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meadstats-staging
  template:
    metadata:
      labels:
        app: meadstats-staging
    spec:
      containers:
      - name: meadstats-staging
        image: registry.bore.ai/meadstats-frontend:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          periodSeconds: 30
          timeoutSeconds: 1
          initialDelaySeconds: 10
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred