apiVersion: v1
kind: Service
metadata:
  name: meadstats
spec:
  selector:
    app: meadstats
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: meadstats-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - meadstats.com
    - www.meadstats.com
    secretName: meadstats-prod-cert
  rules:
    - host: www.meadstats.com
      http:
        paths:
        - backend:
            serviceName: meadstats
            servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meadstats-deployment
  labels:
    app: meadstats
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meadstats
  template:
    metadata:
      labels:
        app: meadstats
    spec:
      containers:
      - name: meadstats
        image: registry.bore.ai/meadstats-frontend:v1.1.0
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          periodSeconds: 30
          timeoutSeconds: 1
          initialDelaySeconds: 10
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred